Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;


namespace MetroAttendanceApp.Models
{

    public class ApplicationUser : IdentityUser
    {

    }
}

Models/ErrorViewModel.cs
using System;

namespace MetroAttendanceApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace MetroAttendanceApp.Models
{


    public class Login
    {
        [Required]
        [EmailAddress]

        public string Email { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

Models/Register.cs
using System.ComponentModel.DataAnnotations;

namespace MetroAttendanceApp.Models
{


    public class Register
    {
        [Required]
        [Display(Name = "Email Address")]

        public string Email { get; set;}

        [Required]
        [Display(Name = "Password")]

        public string Password { get; set; }

        [Required]
        [Display(Name = "Confirm Password")]
        [Compare("Password")]

        public string ConfirmPassword { get; set; }
    }
}

Controllers/AccountsController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MetroAttendanceApp.Models;

namespace MetroAttendanceApp.Controllers
{
    public class AccountsController : Controller
    {
        private readonly ILogger<AccountsController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        
        

        public AccountsController(
            ILogger<AccountsController> logger, 
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _logger = logger;
            _userManager = userManager;
            _signInManager = signInManager;
            
        }
        
        

        [HttpGet]
        public IActionResult ListUsers()
        {
            var users = _userManager.Users;
            return View(users);
        }


            public IActionResult Login()
            {
                return View();
            }

            [HttpPost]
            
            public async Task<IActionResult> Login(Login model)
            {
                try
                {
                     var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, false,
                     lockoutOnFailure: false);

                     if (result.Succeeded)
                     {
                         return RedirectToAction("Index", "Home");
                     }
                     else
                     {
                         ModelState.AddModelError(string.Empty, "Invalid login attemp. Email or Password is wrong");
                         return View();
                     }
                }
                catch (System.Exception)
                {
                    
                    throw;
                }
            }

            public IActionResult Register()
            {
                return View();
            }

            [HttpPost]
            [ValidateAntiForgeryToken]

            public async Task<IActionResult> Register(Register model)
            {
                if (!ModelState.IsValid) return View();

                try
                {
                    ApplicationUser user = await _userManager.FindByEmailAsync(model.Email);
                         if (user == null)
                         {
                             user = new ApplicationUser();
                             user.UserName = model.Email;
                             user.Email = model.Email;

                             IdentityResult result = await _userManager.CreateAsync(user, model.Password);
                             ViewBag.Message = "User was Created";

                             if (result.Succeeded)
                             {
                                 await _userManager.AddToRoleAsync(user, "user");
                                 return RedirectToAction("Login");
                             }
                             else
                             {
                                 ModelState.AddModelError("", "Invalid user details. Add at least One Uppercase, Lowercase, Special Character and Number!");
                                 return View();
                             }

                         }
                         else
                         {
                             ViewBag.Message = "User already Registered";
                             return View();
                         }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(ex.Message,null);
                    return View();
                }
             }
             public async Task<IActionResult> Logout()
             {
                 await _signInManager.SignOutAsync();
                 return RedirectToAction("Index", "Home");
             }

            [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
            public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.
            TraceIdentifier });
        }
        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MetroAttendanceApp.Models;

namespace MetroAttendanceApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }               public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Accounts/ListUsers.cshtml
@model IEnumerable<ApplicationUser>
    @{
        ViewBag.Title = "All Users";
    }

    <h1>All Users</h1>
    
    @if(Model.Any())
    {
        <a asp-action="Register" asp-controller="Account"
        class="btn btn-primary mb-3 style="width:auto">
        Add new user</a>

        foreach(var user in Model)
        {
            <div class="card mb-3">
                <div class="card-header">
                    User Id : @user.Id
                </div>
                <div class="card-body">
                    <h5 class="card-title">@user.UserName</h5>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-danger">Edit</a>
                    <a href="#" class="btn btn-danger">Delete</a>
                </div>
            </div>
        }
    }
    else
    {
        <div class="card">
<div class="card-header">
    No users created yet
</div>
<div class="card-body">
    <h5 class="card-title">
        Use the button below to create a user
    </h5>
    <a class="btn btn-primary" style="width:auto"
    asp-controller="Account" asp-action="Register">
    Add new user</a>
</div>
        </div>
    }

Views/Accounts/Login.cshtml
@model Login;


@{
    ViewData["Title"] = "Login Page";
}



<div class="container">
    <div class="row">
        <h2> Login</h2>
        <div class="col">
        <form asp-controller="Accounts" asp-action="Login" method="post">
            <div asp-validation-summary="All"></div>  
                <input type="email " asp-for="Email" placeholder="Eamil Address">
                <br>
                <input type="password" asp-for="Password" placeholder="Password">
            <br>
            <button type="submit">Login</button>
        </form>
    </div>
</div>

Views/Accounts/Register.cshtml
@model Register;

@{
    ViewData["Title"] = "Register Page";
}



<div class="container">
    <div class="row">
        <h2> Login</h2>
        <div class="col">
            <form asp-controller="Accounts" asp-action="Register" methods="post">
                    <div asp-validation-summary="All"></div>  
                <input type="email " asp-for="Email" placeholder="Eamil Address">
                <br>
                <input type="password" asp-for="Password" placeholder="Password">
                <br>
                <input type="password" asp-for="ConfirmPassword" placeholder="Confirm Password">
                <br>
                <button type="submit">Register</button>
            </form>
        </div>
    </div>
</div>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Page";
}
<h1>@ViewData["Title"]</h1>

<p>This page provides you with basic information about us</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is an Attendance Application</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MetroAttendanceApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Metrosoft AttendanceApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item"> *@
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                        @* </li> *@
                        @* <li class="nav-item"> *@
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                        @* </li> *@
                        @if(SignInManager.IsSignedIn(User) && User.IsInRole("User"))
                    {
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts"
                            asp-action="ListUsers">Users</a>
                        </li>
                    </ul>
                        </div>
                       
                    }
                        
                    </ul>

                    
                    <ul class="navbar-nav mr-auto">

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" 
                            asp-action="Logout">Logout</a>
                        </li>
                        }
                            else
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Login">Login</a>
                        </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MetroAttendanceApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>